{% set name = "xcdat" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/XCDAT/xcdat/archive/v{{ version }}.tar.gz
  sha256: ed6742e0ffa74226c6966f6b2f61d5788f360c4c11c9a8430751315d53381ab2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - cf_xarray >=0.7.3 # Constrained because https://github.com/xarray-contrib/cf-xarray/issues/467
    - cftime
    - dask
    - lxml  # TODO: Remove this in v0.7.0 once cdml/XML support is dropped
    - netcdf4
    - numpy >=1.23.0 # This version of numpy includes support for Python 3.11.
    - pandas
    - python-dateutil
    - xarray >=2022.02.0 # This version of Xarray drops support for Python 3.8.
    - xgcm
  run_constrained:
    - xesmf >=0.7.0 # Constrained because https://github.com/pangeo-data/xESMF/issues/212

test:
  imports:
    - xcdat

about:
  home: https://github.com/XCDAT/xcdat
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Xarray Climate Data Analysis Tools'
  description: |
    An extension of xarray with generalizable climate domain specific functions and utilities.
  doc_url: https://xcdat.readthedocs.io
  dev_url: https://github.com/XCDAT/xcdat

extra:
  recipe-maintainers:
    - jasonb5
    - tomvothecoder
