{% set name = "xcdat" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/XCDAT/xcdat/archive/v{{ version }}.tar.gz
  sha256: fd315cb5806df6476b0f9de8f0e2f76ecf2cbba2cd53dd6ca28d8d6a8e5e9276

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - cf_xarray
    - dask
    - netcdf4
    - numpy
    - pandas
    - xarray

test:
  imports:
    - xcdat

about:
  home: https://github.com/XCDAT/xcdat
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Xarray Extended with Climate Data Analysis Tools'
  description: |
    An extension of xarray with general and climate domain specific functions and utilities.
  doc_url: https://xcdat.readthedocs.io
  dev_url: https://github.com/XCDAT/xcdat

extra:
  recipe-maintainers:
    - tomvothecoder
