{% set name = "xcdat" %}
{% set version = "0.6.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/XCDAT/xcdat/archive/v{{ version }}.tar.gz
  sha256: 934faac41df1d1d7e723e0a91e56753ce4f887fa6433ffceb4abf56b24af837b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - cf_xarray
    - cftime
    - dask
    - lxml
    - netcdf4
    - numpy >=1.23.0 # This version of numpy includes support for Python 3.11.
    - pandas
    - python-dateutil
    - xarray >=2022.02.0 # This version of Xarray drops support for Python 3.8.
    - xgcm
  run_constrained:
    - xesmf >=0.7.0 # Constrained because https://github.com/pangeo-data/xESMF/issues/212.

test:
  imports:
    - xcdat

about:
  home: https://github.com/XCDAT/xcdat
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Xarray Climate Data Analysis Tools'
  description: |
    An extension of xarray with generalizable climate domain specific functions and utilities.
  doc_url: https://xcdat.readthedocs.io
  dev_url: https://github.com/XCDAT/xcdat

extra:
  recipe-maintainers:
    - jasonb5
    - tomvothecoder
