{% set name = "xcdat" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/XCDAT/xcdat/archive/v{{ version }}.tar.gz
  sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - cf_xarray >=0.7.3
    - cftime
    - dask
    - netcdf4
    - numpy >=1.23.0,<2.0
    - pandas
    - python-dateutil
    - xarray >=2022.02.0
    - xesmf >=0.7.0
    - xgcm

test:
  imports:
    - xcdat

about:
  home: https://github.com/XCDAT/xcdat
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Xarray Climate Data Analysis Tools'
  description: |
    An extension of xarray with generalizable climate domain specific functions and utilities.
  doc_url: https://xcdat.readthedocs.io
  dev_url: https://github.com/XCDAT/xcdat

extra:
  recipe-maintainers:
    - jasonb5
    - tomvothecoder
