{% set name = "xcdat" %}
{% set version = "0.9.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/XCDAT/xcdat/archive/v{{ version }}.tar.gz
  sha256: a36b46fe6317fabbac96ed2d4d1c6596a4f11d5069a88f85f683c08cd849faeb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cf_xarray >=0.10.3
    - cftime
    - dask
    - netcdf4
    - numpy >=2.0.0,<3.0.0
    - pandas
    - python-dateutil
    - scipy
    - sparse
    - xarray >=2024.03.0
    - xesmf >=0.8.7
    - xgcm

test:
  requires:
    - python {{ python_min }}
  imports:
    - xcdat

about:
  home: https://github.com/XCDAT/xcdat
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Xarray Climate Data Analysis Tools'
  description: |
    An extension of xarray with generalizable climate domain specific functions and utilities.
  doc_url: https://xcdat.readthedocs.io
  dev_url: https://github.com/XCDAT/xcdat

extra:
  recipe-maintainers:
    - jasonb5
    - tomvothecoder
