{% set name = "xcdat" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/XCDAT/xcdat/archive/v{{ version }}.tar.gz
  sha256: 83a47f265e4e9263ba58a9cb895b72a1f009552c16d7264bc1318d7a75fce44d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - cf_xarray
    - cftime
    - dask
    - lxml
    - netcdf4
    - numpy
    - pandas
    - python-dateutil
    - xarray >=0.21.0
  run_constrained:
    - xesmf >=0.6

test:
  imports:
    - xcdat

about:
  home: https://github.com/XCDAT/xcdat
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Xarray Climate Data Analysis Tools'
  description: |
    An extension of xarray with generalizable climate domain specific functions and utilities.
  doc_url: https://xcdat.readthedocs.io
  dev_url: https://github.com/XCDAT/xcdat

extra:
  recipe-maintainers:
    - jasonb5
    - tomvothecoder
