{% set name = "xcdat" %}
{% set version = "0.10.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/XCDAT/xcdat/archive/v{{ version }}.tar.gz
  sha256: 5c91f7c70dfb2781de00e7e693271004834effcbca7a833813818aba84525e6c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cf_xarray >=0.10.7
    - cftime
    - dask
    - netcdf4
    - numpy >=2.0.0,<3.0.0
    - pandas
    - python-dateutil
    - scipy
    - sparse
    - xarray >=2024.03.0
    - xesmf >=0.8.7
    - xgcm >=0.9.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - xcdat

about:
  home: https://github.com/XCDAT/xcdat
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Xarray Climate Data Analysis Tools'
  description: |
    An extension of xarray with generalizable climate domain specific functions and utilities.
  doc_url: https://xcdat.readthedocs.io
  dev_url: https://github.com/XCDAT/xcdat

extra:
  recipe-maintainers:
    - jasonb5
    - tomvothecoder
